name: Release on push to main

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Compute tag name
      id: compute-tag
      run: |
        echo Computing next tag number
        LASTPATCH=$(git describe --tags | cut -d- -f1 | cut -d. -f3)
        PATCH=$(($LASTPATCH+1))
        echo "::set-output name=tagname::2.1.${PATCH}"

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Build release assets
      run: bundle exec rake book:build

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.compute-tag.outputs.tagname }}
        commit: main
        artifacts: './progit.epub,./progit.mobi,./progit.pdf,./progit.html'
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: './progit.pdf'
        # A file, directory or wildcard pattern that describes what to upload
        
        # The desired behavior if no files are found using the provided path.

        
